#application: dev-dgnet-watchdog
#version: 1
runtime: python27
api_version: 1
threadsafe: True

instance_class: B4
basic_scaling:
  max_instances: 20
  idle_timeout: 3m

handlers:
- url: /.*
  script: watchdog_main.app
