service: stripe-billing
runtime: python37
entrypoint: uwsgi --http-socket :8080 --wsgi-file watchdog_main.py --callable app --master --processes 1 --threads 2

handlers:
- url: /stripe-billing/.*
  script: auto
  secure: always


vpc_access_connector:
  name: "projects/dev-watchdog-user-interface/locations/us-central1/connectors/redis"
