#application: dev-dgnet-watchdog
service: user-interface-tx
runtime: python27
threadsafe: True
api_version: 1
#version: 1

instance_class: F2
automatic_scaling:
  max_pending_latency: 4000ms
  target_cpu_utilization: 0.9
  target_throughput_utilization: 0.95
  max_concurrent_requests: 80  
  
  
  
handlers:
- url: /.*
  script: watchdog_main.app
  login: admin
  
env_variables:
 FIREBASE_URL: https://watchdog-user-interface.firebaseio.com
 FIREBASE_KEY: ab6Sl0lqFBABJzD4LxVQNdBxBAkTopcR8dJ29U0n
 FIREBASE_DOMAIN: watchdog.damianoglobal.com
 FIREBASE_ID: 123
 DEV_FIREBASE_URL: https://dev-watchdog-user-interface.firebaseio.com
 DEV_FIREBASE_KEY: y3DxrFmhJN5gsu6GdKSlj6vRhpT3vvmONCAxYo2I
 DEV_FIREBASE_DOMAIN: dev-watchdog.damianoglobal.com
 DEV_FIREBASE_ID: 123
 EMAIL_API_KEY: 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